import 'package:connectivity/connectivity.dart';
import 'package:cyberhawk/data/WebClient.dart';
import 'package:cyberhawk/model/loginmodel.dart';
import 'package:cyberhawk/model/signupmodel.dart';
import 'package:fluttertoast/fluttertoast.dart';
import 'package:overlay_support/overlay_support.dart';

class Repository {
  Future<Autogenerated> checkPhoneNumber(
      {required String url, dynamic data}) async {
    var connectivityResult = await (Connectivity().checkConnectivity());
    if (connectivityResult == ConnectivityResult.none) {
      Fluttertoast.showToast(
        msg: "No internet connection",
        gravity: ToastGravity.CENTER,
      );
    }
    final dynamic response = await WebClient.post(url, data);
    final Autogenerated userModel = Autogenerated.fromJson(response);
    return userModel;
  }


 Future<SignupModel> signup({required String url, dynamic data}) async {
    var connectivityResult = await (Connectivity().checkConnectivity());
    if (connectivityResult == ConnectivityResult.none) {
      Fluttertoast.showToast(
        msg: "No internet connection",
        gravity: ToastGravity.CENTER,
      );
    }
    final dynamic response = await WebClient.post(url, data);
    final SignupModel generateOtpModel = SignupModel.fromJson(response);
    return generateOtpModel;
  }
  Future<Autogenerated> generateOtp({required String url, dynamic data}) async {
    var connectivityResult = await (Connectivity().checkConnectivity());
    if (connectivityResult == ConnectivityResult.none) {
      Fluttertoast.showToast(
        msg: "No internet connection",
        gravity: ToastGravity.CENTER,
      );
    }
    final dynamic response = await WebClient.post(url, data);
    final Autogenerated generateOtpModel = Autogenerated.fromJson(response);
    return generateOtpModel;
  }

  Future<Autogenerated> loginWithOtp(
      {required String url, dynamic data}) async {
    var connectivityResult = await (Connectivity().checkConnectivity());
    if (connectivityResult == ConnectivityResult.none) {
      Fluttertoast.showToast(
        msg: "No internet connection",
        gravity: ToastGravity.CENTER,
      );
    }
    final dynamic response = await WebClient.post(url, data);
    final Autogenerated loginModel = Autogenerated.fromJson(response);
    return loginModel;
  }
}
