class Autogenerated {
  bool? status;
  String? msg;
  DATA? dATA;
  String? token;

  Autogenerated({this.status, this.msg, this.dATA, this.token});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    msg = json['msg'];
    dATA = json['DATA'] != null ? new DATA.fromJson(json['DATA']) : null;
    token = json['token'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['status'] = status;
    data['msg'] = msg;
    if (dATA != null) {
      data['DATA'] = dATA!.toJson();
    }
    data['token'] = token;
    return data;
  }
}

class DATA {
  String? sId;
  String? role;
  int? usertype;
  bool? isAssigned;
  int? phone;
  bool? phoneVerified;
  bool? emailVerified;
  bool? ispasswordChanged;
  bool? isprofileUpdated;
  int? profileCompletionLevel;
  String? status;
  String? cartType;
  int? level;
  String? remarks;
  List<Null>? address;
  String? createDate;
  String? updateDate;
  int? iV;

  DATA(
      {this.sId,
      this.role,
      this.usertype,
      this.isAssigned,
      this.phone,
      this.phoneVerified,
      this.emailVerified,
      this.ispasswordChanged,
      this.isprofileUpdated,
      this.profileCompletionLevel,
      this.status,
      this.cartType,
      this.level,
      this.remarks,
      this.address,
      this.createDate,
      this.updateDate,
      this.iV});

  DATA.fromJson(Map<String, dynamic> json) {
    sId = json['_id'];
    role = json['role'];
    usertype = json['usertype'];
    isAssigned = json['isAssigned'];
    phone = json['phone'];
    phoneVerified = json['phoneVerified'];
    emailVerified = json['emailVerified'];
    ispasswordChanged = json['ispasswordChanged'];
    isprofileUpdated = json['isprofileUpdated'];
    profileCompletionLevel = json['profileCompletionLevel'];
    status = json['status'];
    cartType = json['cartType'];
    level = json['level'];
    remarks = json['remarks'];
    if (json['address'] != null) {
      address = <Null>[];
    }
    createDate = json['create_date'];
    updateDate = json['update_date'];
    iV = json['__v'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['_id'] = sId;
    data['role'] = role;
    data['usertype'] = usertype;
    data['isAssigned'] = isAssigned;
    data['phone'] = phone;
    data['phoneVerified'] = phoneVerified;
    data['emailVerified'] = emailVerified;
    data['ispasswordChanged'] = ispasswordChanged;
    data['isprofileUpdated'] = isprofileUpdated;
    data['profileCompletionLevel'] = profileCompletionLevel;
    data['status'] = status;
    data['cartType'] = cartType;
    data['level'] = level;
    data['remarks'] = remarks;
    if (address != null) {
      data['address'] = address;
    }
    data['create_date'] = createDate;
    data['update_date'] = updateDate;
    data['__v'] = iV;
    return data;
  }
}
